dequelabs/react-axe

index.js
PR as discussed in this issue https://github.com/dylanb/react-axe/issues/4
=> check the whole DOM when testing, not only body

README.md
remove a bunch of spaces in the code examples and colorize :) thanks for the module
=> lint readme

circle.yml, package.json
This patch adds a `circle.yml` file for running our test suite and caching our dependencies.
NOTE: I have "followed" `dequelabs/react-axe` on CircleCI in order to enable the project.
Closes #29.
/cc @WilcoFiers
=> chore: setup CircleCI

index.js
A previous commit (1d4bd8db521d38f4fba831e3066339dc21d31325) removed our pseudo-semaphore which prevented us from running aXe concurrently. This patch adds back our "timer" semaphore and ensures we do not can `axe.run()` more than once on the same tick.
Closes #32.
=> fix: use a semaphore to avoid running axe concurrently

README.md
=> docs: add back debouncing

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
=> chore: Add .github template

README.md
Closes https://github.com/dequelabs/react-axe/issues/36
=> doc: Add intro to README

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, circle.yml, cypress.json, example/package.json, greenkeeper.json, index.js, package-lock.json, package.json
NOTE: I was unable to use the `pr-release` script here, so this was done manually. Sorry if I forgot something, but the script was erroring due to commit messages.
---
=> Release v3.0.2

CHANGELOG.md, package-lock.json, package.json
<< Describe the changes >>
Closes issue:
=> Chore: Update from Master

package-lock.json, package.json
Prevents a security warning (see https://nvd.nist.gov/vuln/detail/CVE-2018-6341)
=> chore: upgrade react and react-dom dev deps

.circleci/config.yml, CHANGELOG.md, README.md, cypress.json, cypress/integration/index-test.js, cypress/support/index.js, example/package.json, example/src/serviceChooser.js, index.js, package-lock.json, package.json
=> chore: Release v3.2.0

example/package.json, package-lock.json, package.json
=> chore: update axe-core to v3.3.0

index.js
<< Describe the changes >>
Closes issue: https://github.com/dequelabs/react-axe/issues/103
=> Fix premature unmount bug

.github/PULL_REQUEST_TEMPLATE.md
Align the PR template with other repos.
=> chore: Simplify PR template

.circleci/config.yml, example/package.json
=> ci: bust cache and add missing dependency `styled-components`

README.md, index.js
Add Axe-core context to reactAxe-parameters.
Closes issue:
#41 
=> feat: Support Axe-core context param

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, example/package.json, index.js, package-lock.json, package.json
=> Release 3.4.0

CHANGELOG.md, README.md, index.js, package-lock.json, package.json
Want to get the performance changes in
Reviewer checks
=> chore(release): 3.4.1

example/src/example.js, example/src/globalHeader.js, example/src/service.js, example/src/serviceChooser.js, package.json
The example stopped working in the latest version of Chrome (as well as Firefox and Safari). Updated the examples to use more modern React syntax.
Also forgot to add the `tsc` call so the project could built locally.
=> docs: fix example for modern browsers

.circleci/config.yml
YAML is awful
<< Describe the changes >>
Closes issue:
=> ci: Fix "canary_release" job

package.json
=> fix: explicitly include dist files in npm tarball

.circleci/canary-version.js, .circleci/config.yml, .npmignore, CHANGELOG.md, package-lock.json, package.json
Hopefully this works this time.
=> Release 3.5.1

.npmignore
I have no idea what's going on 🤷 
=> chore: Explicitly negate the `dist` directory

package.json
I HAVE NO IDEA WAHTS GOING ON!!!!
🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 🤷 …
=> chore: Remove `files` from package.json

package.json
=> chore: Remove example stuff from "prepare" script

package.json
Reverts dequelabs/react-axe#164
Didn't work. I think #165 will do it. 🤷
=> chore: Revert "chore: Remove `files` from package.json"

example/package.json
=> chore: upgrade http-server to fix http-proxy vulnerability
